#include <stdio.h>
#include <math.h>
#include <stdint.h>

int main( int argc, char *argv[])
{
	printf("Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n");
	printf("1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n");
	printf("By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n\n");

	printf("Somehow I was worried it would not fit into a 32 bit int, leaving this here for future reference.\n");
	printf("2^32: %u\n", (unsigned int)pow(2,32));
	printf("2^64: %lu\n", (uint64_t)pow(2,64));

	unsigned int one = 1;
	unsigned int two = 2;
	unsigned int sum = 0;
	while( two < 4000000 )
	{
		if( (two & 1) == 0) sum += two; 
		unsigned int tmp = one;
		one = two;
		two = one + tmp;
	}
	printf("Answer: %lu\n", sum);
	return 0;
}
